services:
  firebase-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: >
      gcloud emulators firestore start
      --host-port=0.0.0.0:8081
      --database-mode=datastore-mode
      --project=demo-azadi
    ports:
      - "8081:8081"
