server.port=8080
datastore.host=
gcp.project.id=demo-azadi
firestore.db=azadi
use.adc=false
cookie.secure=true
demo.mode=false
template.cache=true
rate.limit.general=60
stripe.api.key=
stripe.webhook.secret=
stripe.api.base=
vite.stripe.publishable.key=
azadi.encryption.key=
azadi.encryption.salt=
resend.api.key=
resend.from.email=noreply@junaid.guru
resend.api.url=https://api.resend.com/emails
